package rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import rest.db.Usuarios;
import rest.db.UsuariosRepository;
import rest.db.TimeCoracao;
import rest.db.TimeCoracaoRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UsuariosRepository usuariosRepository;
	private TimeCoracaoRepository timeCoracaoRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String nomeCompleto
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Usuarios n = new Usuarios();
		n.setNomeCompleto(nomeCompleto);
		n.setEmail(email);
		usuariosRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Usuarios> getAllUsers() {
		// This returns a JSON or XML with the users
		return usuariosRepository.findAll();
	}

	@GetMapping(path="/createTime")
	public @ResponseBody String createNewTime(@RequestParam String nomeTime){

		TimeCoracao tc = new TimeCoracao();
		tc.setNomeTime(nomeTime);
		System.out.print(tc.toString());
		timeCoracaoRepository.save(tc);
		return "Time Cadastrado com sucesso! :)";
	}
}